myportfolio/urls.py
from re import template
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('',include('users.urls')),

   path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns=[
    path('',views.projects,name ='projects'),
    path('project/<str:pk>/',views.project, name='project'),
    path('create-project/',views.createProject, name= 'create-project'),
    path('update-project/<str:pk>/',views.updateProject, name= 'update-project'),
    path('delete-project/<str:pk>/',views.deleteProject, name= 'delete-project'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('',views.profiles,name='profile-all'),
    path('profile/<str:pk>/',views.profile,name='single-profile'),
    
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/',views.registerUser,name='register'),

    path('account/',views.userAccount,name='account'),
    path('edit-account/',views.editAccount,name='edit-account'),
 

    path('create-skill/',views.createSkill,name='create-skill'),
    path('update-skill/<str:id>/',views.updateSkill,name='update-skill'),
    path('delete-skill/<str:id>/',views.deleteSkill,name='delete-skill'),

    path('inbox/',views.inbox, name='inbox'),
    path('view-message/<str:pk>/',views.viewMessage,name='view-message'),
    path('create-message/<str:pk>/',views.createMessage,name='create-message'),

    #path('editprofile-class/',views.ProfileEditView.as_view(),name='allprofile-class'),


]

projects/models.py
from email.policy import default
from django.utils import timezone
from django.db import models

from users.models import Profile

# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True,blank=True)
    title = models.CharField(max_length=200) 
    image = models.ImageField(upload_to='photos/',null=True ,blank=True, default='website.jpg')
    description = models.TextField(null=True,blank=True)
    demo_link = models.CharField(max_length=2000,null=True,blank=True)
    source_link= models.CharField(max_length=2000,null=True,blank=True)
    tags = models.ManyToManyField('Tag',blank=True)
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(default = timezone.now)
    vote_total = models.IntegerField(default=0,blank=True,null=True)
    vote_ratio = models.IntegerField(default=0,blank=True,null=True)


    def __str__(self):
        return self.title


class Review(models.Model):
    Vote_type = [('up','Up Vote'),
                 ('down','Down Vote'),
                ]
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True,blank=True)

    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True,blank=True)
    value = models.CharField(max_length=100,choices=Vote_type)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.value

   
    

class Tag(models.Model):

    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

users/models.py
from django.db import models

from django.contrib.auth.models import User




# Create your models here.

class Profile(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name= models.CharField(max_length=200,null=True,blank=True)
    username = models.CharField(max_length=200,null=True,blank=True)
    location = models.CharField(max_length=200,null=True,blank=True)
    email = models.EmailField(blank=True,null=True)
    short_intro = models.CharField(max_length=200,null=True,blank=True)
    bio = models.TextField(null=True,blank=True)
    profile_image = models.ImageField(upload_to = 'profiles/',default='profiles/user-default.png' )
    social_github = models.CharField(max_length=200,null=True,blank=True)
    social_twitter = models.CharField(max_length=200,null=True,blank=True)
    social_youtube = models.CharField(max_length=200,null=True,blank=True)
    social_linkedin = models.CharField(max_length=200,null=True,blank=True)
    social_website = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self): 
        return self.username


class Skill(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=200,null=True,blank=True)
    description  = models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
    recipient = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True, blank=True,related_name='messages')
    name= models.CharField(max_length=200,null=True,blank=True)
    email = models.EmailField(max_length=200,blank=True,null=True)
    subject = models.CharField(max_length=200,null=True,blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False,null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
    

projects/forms.py
from django.forms import ModelForm,models
from .models import Project,Review
from django import forms

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        #fields = '__all__'
        fields = ['name','image','description','demo_link','source_link','Tag']
        widgets={
            'Tag':forms.CheckboxSelectMultiple(),
        }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value','body']
        labels = {
            'value':'Add your vote for the Comment',
            'body':'Add your comments here'
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input input--text','placeholder':'Enter Value'})
           

projects/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from django.http import HttpResponse

from projects.utils import searchProjects
from .models import Project,Review,Tag
from .forms import ProjectForm

# Create your views here.

projectsList = [
    {
        'id': '1',
        'title': 'Ecommerce Website',
        'description': 'Fully functional ecommerce website'
    },
    {
        'id': '2',
        'title': 'Portfolio Website',
        'description': 'A personal website to write articles and display work'
    },
    {
        'id': '3',
        'title': 'Social Network',
        'description': 'An open source project built by the community'
    }
]


def projects(request):
    # d_val = datetime.now()
    # context = { 'proj_list' : projectsList,
    #             'number' : 10, 
    #             'date_val':  d_val,
    #              }
    project_list  = Project.objects.all()
    project_list, search_query  = searchProjects(request)
    context = {'projects':project_list}


    return render(request,'projects.html',context)

def project(request,pk):
    proj = None
    proj = Project.objects.get(id=pk)
    # for p_dict in projectsList:
    #     if p_dict['id'] == pk:
    #         proj_dict = p_dict
     
    context ={'proj' : proj,}
    return render(request,'single-project.html',context)



def createProject(request):
    form  = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')

    context = {'form':form}
    return render(request,'create-project.html',context)


def updateProject(request,pk):
    proj = Project.objects.get(id=pk)
    proj_form =ProjectForm(instance =proj)
    
    if request.method == 'POST':
        proj_form = ProjectForm(request.POST,request.FILES, instance =proj)
        
        if proj_form.is_valid():
            proj_form.save()
            print('Image saved in database')
            return redirect('projects:projects')

    context = {'project_form':proj_form}
    return render(request,'update-project.html',context)


def deleteProject(request,pk):
    proj = Project.objects.get(id=pk)

    if request.method == 'POST':
        
        proj.delete()
        return redirect('projects:projects')

    context ={'project' : proj}

    return render(request,'delete-project.html',context)

users/views.py
from email.message import Message
from multiprocessing import context
from django.shortcuts import redirect, render
from .models import Profile
from projects.models import Project
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from .forms import ProfileForm,SkillForm,MessageForm
from .utils import searchProfiles,paginateProfiles


# Create your views here.


def profiles(request):
    #profiles = Profile.objects.all()
    profiles, search_query = searchProfiles(request)
    profiles,custom_range =paginateProfiles(request,profiles,3)
    context = {
        'profiles':profiles,
        'search_query':search_query,
        'custom_range':custom_range,
        }
    return render(request,'users/profile-all.html',context)



def profile(request, pk):
    profile = Profile.objects.get(id=pk)
    top_skills = profile.skill_set.exclude(description__iexact="")
    other_skills = profile.skill_set.filter(description="")

    #projects = Project.objects.filter(id=pk)
    
    context = {'profile': profile,
               'topskills': top_skills,
               'otherskills': other_skills,
               #'projects': Projects,
               }
    return render(request, 'users/single-profile.html', context)


# def loginUser(request):
#     page = 'login'
    
#     if request.method == 'POST':
#         username = request.POST['username'].lower()
#         password = request.POST['password']

#         try:
#             user = User.objects.get(username=username)
#         except:
#             messages.error(request, 'User does not exist')

#         user = authenticate(request, username=username, password=password)

#         if user is not None:
#             login(request, user)
            

#             return redirect(request.GET['next'] if 'next' in request.GET else 'users:account')
#         else:
#             messages.error(request, "Username or Password doesn't match")
           
#     context = {'page': page}
#     return render(request, 'users/login_register.html', context)


def loginUser(request):
    page = 'login'
    if request.method =='POST':
        username= request.POST['username']
        password = request.POST['password']
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,'User is not available')

        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('users:profile-all')
        else:
            messages.error(request,"username and password doesn't match")
    context = {
        'page':page,
    }

    return render(request,'users/login_register.html',context)

def logoutUser(request):
    logout(request)
    messages.info(request, 'User successfully logged out!')
    return redirect('users:login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()
    context = {'page': page,
               'form': form
               }

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user=form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'User created successfully')
            login(request, user)
            return redirect('users:profile-all')
        else:
            messages.error(
                request, 'Some error occurred during registration')
            print(form.errors)
    

    context={'page':page, 'form':form, }      
    return render(request, 'users/login_register.html', context)


def userAccount(request):
    profile = request.user.profile
    context={
        'profile':profile,
    }
    return render(request,'users/account.html',context)



def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST,request.FILES,instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request,'Profile updated Successfully')
            return redirect('users:account')
        else:
            messages.error(request,'Enter valid data in fields')   

    context={'form':form}
    return render(request,'users/profile-form.html',context)





def createSkill(request):
    profile = request.user.profile
    form = SkillForm()

    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request,'Skill created Successflly')
            return redirect('users:account')
        else:
            messages.error(request,'Some error occurred')


    context = {'form':form}
    return render(request,'users/skill-form.html',context)




def updateSkill(request,id):
    profile = request.user.profile
    skill = profile.skill_set.get(id=id)
    form = SkillForm(instance = skill)

    if request.method == 'POST':
        form = SkillForm(request.POST,instance=skill)
        if form.is_valid():
            form.save()
                       
            messages.success(request,'Skill updated Successflly')
            return redirect('users:account')
        else:
            messages.error(request,'Some error occurred')


    context = {'form':form}
    return render(request,'users/skill-form.html',context)





def deleteSkill(request,id):
    profile = request.user.profile
    skill = profile.skill_set.get(id=id)

    if request.method == 'POST':
        skill.delete()
        messages.success(request,'skill deleted successfully')
        return redirect('users:account')

    context = {'object':skill}
    return render(request,'delete-form.html',context)

#@login_required(Login_url='users:login')
def inbox(request):
    recipient = request.user.profile
    recieved_msgs = recipient.messages.all()
    unreadCount = recieved_msgs.filter(is_read=False).count()

    context = {'recieved_msgs':recieved_msgs, 'unreadCount':unreadCount}
    return render(request,'users/inbox.html',context)

#@login_required(Login_url='users:login')
def viewMessage(request,pk):
    message = Message.objects.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()

    context= {'message':message}
    return render(request,'users/message.html',context)

def createMessage(request,pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        try:
            sender = request.user.profile
        except:
            sender = None
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email

            message.save()
            return redirect('users:profile-all')

    context = {'form':form, 'recipient':recipient}
    return render(request,'users/message-form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}

{% block content  %}

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.profile_location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
              
                
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">

            {% for skill in profile.skill_set.all  %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                 {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:update-skill' skill.id %}" ><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:delete-skill' skill.id %}?next=/users/account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>

            {% endfor %}
           
            
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">

            {% for project in profile.project_set.all  %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects:project' project.id  %}"><img src="{{project.img.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="single-project.html">{{project.name}}</a>
                <p>
                  {{project.description|truncatewords:20}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:update-project' project.id  %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete-project' project.id  %}?next=/users/account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor  %}           

          </table>
        </div>
      </div>
    </div>
  </main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}
{% block content %} 
  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
          {% for msg in recieved_msgs %} 
          {% if msg.is_read == False %} 
        <li class="message message--unread">
            {% else %}
            <li class="message">
            {% endif %} 
          <a href="{% url 'users:view-message' msg.id %}">
            <span class="message__author">{{msg.name}}</span>
            <span class="message__subject">{{msg.subject}}</span>
            <span class="message__date">{{msg.created}}</span>
          </a>
        </li>
        {% endfor %} 
      </ul>
    </div>
  </main>
{% endblock %} 

users/templates/users/message-form.html
{% extends 'main.html' %}
{% block content %} 

<!-- Main Section -->
<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:single-profile' recipient.id %}"><i class="im im-angle-left"></i></a>
        <hr>
        <form class="form" method="POST">
            {% csrf_token %} 
            {% if request.user.is_authenticated == True %} 
            <div class="form__field">
                <label for="formInput#text">{{form.name.label}}</label>
                {{form.name}}
                
            </div>
            <div class="form__field">
                <label for="formInput#text">{{form.email.label}}</label>
                {{form.email}}
            </div>
            <div class="form__field">
                <label for="formInput#text">{{form.subject.label}}</label>
                {{form.subject}}
            </div>
            <div class="form__field">
                <label for="formInput#text">{{form.body.label}}</label>
                {{form.body}}
            </div>
            {% endif %}
            <input class="btm btm--sub btn--lg my-md" type="submit" value="Submit"/>
            

        </form>
      </div>
    </div>
  </main>
{% endblock %} 

users/templates/users/projects.html
{% extends 'main1.html'  %}

{% block content %}
   <p>List of Projects</p> 
   <table style="border: 2px groove blue;">
      <tr >
         <th>ID</th>
         <th>Project Name</th>
         <th>Votes</th>
         <th>Positive Votes (%)</th>
         <th>View</th>
      </tr >
      {% for p in projects %}
         <tr>
            <td>
               {{p.id}}
            </td>
            <td>
               {{p.title}}
            </td>
            <td>
               {{p.vote_total}}
            </td>
            <td>
               {{p.vote_ratio}}
            </td>
            <td>
               <a href="{% url 'projects:project' p.id %}">view</a>
            </td>
            <td>
               <a href="{% url 'projects:update-project' p.id %}">Edit</a>
            </td>
            <td>
               <a href="{% url 'projects:delete-project' p.id %}">Delete</a>
            </td>
            
         </tr>
                                    
         <!-- <p> -- <a href="{% url 'projects:project' p.id %}">{{p.title | title}} </a>--{{p.description|truncatewords:3 }}</p>
    -->
      {% endfor %}

      
   </table>

   <!-- Main Section -->
  <main class="projects">
   <section class="hero-section text-center">
     <div class="container container--narrow">
       <div class="hero-section__box">
         <h2>Search for <span>Projects</span></h2>
       </div>

       <div class="hero-section__search">
         <form class="form" action="#" method="get">
           <div class="form__field">
             <label for="formInput#search">Search By Projects </label>
             <input class="input input--text" id="formInput#search" type="text" name="text"
               placeholder= "Search by Project Title" />
           </div>

           <input class="btn btn--sub btn--lg" type="submit" value="Search" />
         </form>
       </div>
     </div>
   </section>
   <!-- Search Result: DevList -->
   <section class="projectsList">
     <div class="container">
       <div class="grid grid--three">

         {% for p in projects %}
         <div class="column">
           <div class="card project">
             <a href="{% url 'projects:project' p.id %}" class="project">
               <img class="project__thumbnail" src="{{p.image.url}}" alt="project thumbnail" />
               <div class="card__body">
                 <h3 class="project__title">{{p.title|slice:"20"}}</h3>
                 <p><a class="project__author" href="">By Dennis Ivanov</a></p>
                 <p class="project--rating">
                   <span style="font-weight: bold;">{{p.vote_ratio}}%</span> Postitive
                   Feedback ({{p.vote_total}}Votes)
                 </p>
                 <div class="project__tags">
                  {% for tag in p.tags.all|slice:"3" %}
                   <span class="tag tag--pill tag--main">
                     <small>{{ tag }}</small>
                   </span>
                  {% endfor %}
                 
                 </div>
               </div>
             </a>
           </div>
         </div>
         {% endfor %}

       

         

         


        

       </div>
     </div>
   </section>

 </main>


   


{% endblock %}

users/templates/users/single-profile.html
{% extends 'main.html' %}
{% block content %}


  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
              
                
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="{% url 'users:create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>


            <div class="devInfo__skills">
              {% for skill in topskills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
              {% endfor %}
             
             

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherskills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
                
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for proj in project %}

              <div class="column">
                <div class="card project">
                  <a href=" {% url 'projects:project' proj.id %} " class="project">
                    <img class="project__thumbnail" src="{{proj.img.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{proj.name}}</h3>
                      <p><a class="project__author" href="{% url 'users:single-profile' proj.owner.id %}">{{proj.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{proj.vote_ratio}}%</span> Postitive
                        Feedback ({{proj.vote_total}} Vote {{proj.vote_total|pluralize:"s"}} )
                      </p>


                      <div class="project__tags">
                        {% for tag in proj.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                        
                      </div>
                    </div>
                  </a>
                </div>
              </div>

              {% endfor %}

             


            </div>
          </div>
        </div>
      </div>
    </div>
  </main>


{% endblock  %}