myportfolio/urls.py
from re import template
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('',include('users.urls')),

   path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
        name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns=[
    path('',views.projects,name ='projects'),
    path('project/<str:pk>/',views.project, name='project'),
    path('create-project/',views.createProject, name= 'create-project'),
    path('update-project/<str:pk>/',views.updateProject, name= 'update-project'),
    path('delete-project/<str:pk>/',views.deleteProject, name= 'delete-project'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('',views.profiles,name='profile-all'),
    path('profile/<str:pk>/',views.profile,name='single-profile'),
    
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/',views.registerUser,name='register'),

    path('account/',views.userAccount,name='account'),
    path('edit-account/',views.editAccount,name='edit-account'),
 

    path('create-skill/',views.createSkill,name='create-skill'),
    path('update-skill/<str:id>/',views.updateSkill,name='update-skill'),
    path('delete-skill/<str:id>/',views.deleteSkill,name='delete-skill'),

    path('inbox/',views.inbox, name='inbox'),
    path('view-message/<str:pk>/',views.viewMessage,name='view-message'),
    path('create-message/<str:pk>/',views.createMessage,name='create-message'),

    #path('editprofile-class/',views.ProfileEditView.as_view(),name='allprofile-class'),


]

projects/models.py
from email.policy import default
from django.utils import timezone
from django.db import models

from users.models import Profile

# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True,blank=True)
    title = models.CharField(max_length=200) 
    image = models.ImageField(upload_to='photos/',null=True ,blank=True, default='website.jpg')
    description = models.TextField(null=True,blank=True)
    demo_link = models.CharField(max_length=2000,null=True,blank=True)
    source_link= models.CharField(max_length=2000,null=True,blank=True)
    tags = models.ManyToManyField('Tag',blank=True)
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(default = timezone.now)
    vote_total = models.IntegerField(default=0,blank=True,null=True)
    vote_ratio = models.IntegerField(default=0,blank=True,null=True)


    def __str__(self):
        return self.title


class Review(models.Model):
    Vote_type = [('up','Up Vote'),
                 ('down','Down Vote'),
                ]
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True,blank=True)

    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True,blank=True)
    value = models.CharField(max_length=100,choices=Vote_type)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.value

   
    

class Tag(models.Model):

    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

projects/forms.py
from django.forms import ModelForm,models
from .models import Project,Review
from django import forms

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        #fields = '__all__'
        fields = ['name','image','description','demo_link','source_link','Tag']
        widgets={
            'Tag':forms.CheckboxSelectMultiple(),
        }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value','body']
        labels = {
            'value':'Add your vote for the Comment',
            'body':'Add your comments here'
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input input--text','placeholder':'Enter Value'})
           

projects/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from django.http import HttpResponse

from projects.utils import searchProjects
from .models import Project,Review,Tag
from .forms import ProjectForm

# Create your views here.

projectsList = [
    {
        'id': '1',
        'title': 'Ecommerce Website',
        'description': 'Fully functional ecommerce website'
    },
    {
        'id': '2',
        'title': 'Portfolio Website',
        'description': 'A personal website to write articles and display work'
    },
    {
        'id': '3',
        'title': 'Social Network',
        'description': 'An open source project built by the community'
    }
]


def projects(request):
    # d_val = datetime.now()
    # context = { 'proj_list' : projectsList,
    #             'number' : 10, 
    #             'date_val':  d_val,
    #              }
    project_list  = Project.objects.all()
    project_list, search_query  = searchProjects(request)
    context = {'projects':project_list}


    return render(request,'projects.html',context)

def project(request,pk):
    proj = None
    proj = Project.objects.get(id=pk)
    # for p_dict in projectsList:
    #     if p_dict['id'] == pk:
    #         proj_dict = p_dict
     
    context ={'proj' : proj,}
    return render(request,'single-project.html',context)



def createProject(request):
    form  = ProjectForm()

    if request.method == 'POST':
        form = ProjectForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')

    context = {'form':form}
    return render(request,'create-project.html',context)


def updateProject(request,pk):
    proj = Project.objects.get(id=pk)
    proj_form =ProjectForm(instance =proj)
    
    if request.method == 'POST':
        proj_form = ProjectForm(request.POST,request.FILES, instance =proj)
        
        if proj_form.is_valid():
            proj_form.save()
            print('Image saved in database')
            return redirect('projects:projects')

    context = {'project_form':proj_form}
    return render(request,'update-project.html',context)


def deleteProject(request,pk):
    proj = Project.objects.get(id=pk)

    if request.method == 'POST':
        
        proj.delete()
        return redirect('projects:projects')

    context ={'project' : proj}

    return render(request,'delete-project.html',context)

templates/create-project.html
{% extends 'main.html'  %}

{% block content %}

    <!-- <form action="" method="POST"  enctype="multipart/form-data"  >
        {% csrf_token %}
        {{ form.as_p  }}
        <input type="submit" value="Submit">
    </form> -->

  <!-- Main Section -->
  <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data" >

                {% csrf_token %}
                <!-- Input:Text -->

                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}} </label>
                    {{field}}
                </div>
                {% endfor %}                       
               
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>


{% endblock %}

templates/delete-project.html
{% extends 'main.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
    <p>
        Are you sure you want to delete {{project.title}} ?
    </p>

    <input type="submit" value="Submit">
    <button><a href=" {% url 'projects:projects' %}  ">Cancel</a></button>
</form>

{% endblock %}

templates/form-template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="uikit/styles/uikit.css" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="styles/app.css" />

    <title>DevSearch - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="/" class="header__logo">
                <img src="images/logo.svg" alt="DevSearch Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="index.html">Developers</a></li>
                    <li class="header__menuItem"><a href="projects.html">Projects</a></li>
                    <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
                    <li class="header__menuItem"><a href="account.html">My Account</a></li>
                    <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

   
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static 'style/app.css' %}" />

        <title>DevSearch - Connect with Developers!</title>
        
   
</head>

<body>
    <script src="{% static 'uikit/app.js' %}" ></script>
    {% include 'nar-bar.html' %}

    <!-- {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %} -->

    {% if messages %}
    {% for message in messages %}
    <div id="button" class="alert alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button onclick="closebutton()" class="alert__close" >x</button>
     
    </div>
    
    {% endfor %}

    {% endif %}

    <hr>
    {% block content %}

    {% endblock %}
    <p>
        Footer
    </p>
    <script src="{% static 'uikit/app.js' %}" ></script>
    <script src="{% static 'js/proj.js' %}" ></script>
</body>

</html>

templates/nar-bar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
      <a href=" {% url 'projects:projects' %} " class="header__logo">
        <img src="{% static 'images/logo.jpg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'users:profile-all'  %}">Developers</a></li>
          <li class="header__menuItem"><a href=" {% url 'projects:projects'  %} ">Projects</a></li>
          <li class="header__menuItem"><a href="{% url 'users:inbox' %}">Inbox</a></li>
         
          {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'users:account' %} ">My Account</a></li>
          <li class="header__menuItem"><a href="{% url 'users:logout' %} " class="btn btn--sub">Logout</a></li>
          {% else %}
          <li class="header__menuItem"><a href="{% url 'users:login' %} " class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
    <ul class="container">
    {% if queryset.has_previous %}
    <li><a href="?page={{queryset.previous_page_number}}&search_query={{search_query}}" class="btn page-link">&#10094;Prev</a></li>
    {% endif %}

    {% for page in custom_range %}
    {% if page == queryset.number %}
    <li><a href="?page={{page}}&search_query={{search_query}}" class="btn page-link btn--sub">{{page}}</a></li>
    {% else %}
    <li><a href="?page={{page}}&search_query={{search_query}}" class="btn page-link">{{page}}</a></li>

    {% endif %}

    {% endfor %}
    {% if queryset.has_next %}
    <li><a href="?page={{queryset.next_page_number}}&search_query={{search_query}}" class="btn page-link">Next&#10095</a></li>

    {% endif %}


    </ul>

</div>





{% endif %}

templates/password_reset.html
{% extends 'main.html' %} 
{% block content %} 

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'],
    input[type='number'] {
        min-width: 24rem;
        width: 100%;
        padding: 1.2rem 1.5rem;
        border-radius: 0.5rem;
        border: 2px solid var(--color - light);
        transition: all 0.3s ease -in -out;
        background-color: var(--color - bg);
    }
    input[type='text']:focus,
    input[type='email']:focus,
    input[type='password']:focus,
    input[type='number']:focus,
    input[type='text']:active,
    input[type='email']:active,
    input[type='password']:active,
    input[type='number']:active {
        outline: none;
        border: 2px solid var(--color - main);
    }

</style>
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>password reset</h3>
            <p>forgotten your password? enter your mail address below and
               well email instructions for setting a new one</p>
            <br>
            <form class="form" method="POST">
                {% csrf_token %} 
                {{form.as_p}}
                <input class="btn btn--sub btn--lg my-md" type="submit" value="Submit">
                
            </form>
        </div>
    </div>
</main>
{% endblock %} 

templates/password_reset_complete.html
{% extends 'main.html' %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            
            <h3>Password reset complete </h3>
            <p>Your password has been set. You may go ahead and log in now.</p>
            <a class="btn btn--sub btn--lg  my-md" href="{% url 'users:login' %}">Login</a>

           
        </div>
    </div>
</main>

{% endblock %}

templates/password_reset_confirm.html
{% extends 'main.html' %}
{% block content %}
<style>
    input[type='text'],
    input[type='email'],
    input[type='password'],
    input[type='number']{
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input[type='text']:focus,
input[type='email']:focus,
input[type='password']:focus,
input[type='number']:focus,
input[type='text']:active,
input[type='email']:active,
input[type='password']:active,
input[type='number']:active {
  outline: none;
  border: 2px solid var(--color-main);
}
</style>
<!-- Main Section -->
    
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            
            <h3>Enter new password</h3>
            <p>Please enter your new password twice so we can verify you typed it in correctly.
            </p>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="change my password" />
            </form>
        </div>
    </div>
</main>



{% endblock %}

templates/password_reset_sent.html
{% extends 'main.html' %} 
{% block content %} 

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>password reset sent </h3>
            <p>
                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
            </p>
            <br>
            <p>
                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
            </p>
            <form class="form" method="POST">
                {% csrf_token %} 
                {{form.as_p}}
                <input class="btn btn--sub btn--lg my-md" type="submit" value="Submit">
                
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/projects.html
{% extends 'main.html'  %}

{% block content %}
   <p>List of Projects</p> 
   <table style="border: 2px groove blue;">
      <tr >
         <th>ID</th>
         <th>Project Name</th>
         <th>Votes</th>
         <th>Positive Votes (%)</th>
         <th>View</th>
      </tr >
      {% for p in projects %}
         <tr>
            <td>
               {{p.id}}
            </td>
            <td>
               {{p.title}}
            </td>
            <td>
               {{p.vote_total}}
            </td>
            <td>
               {{p.vote_ratio}}
            </td>
            <td>
               <a href="{% url 'projects:project' p.id %}">view</a>
            </td>
            <td>
               <a href="{% url 'projects:update-project' p.id %}">Edit</a>
            </td>
            <td>
               <a href="{% url 'projects:delete-project' p.id %}">Delete</a>
            </td>
            
         </tr>
                                    
         <!-- <p> -- <a href="{% url 'projects:project' p.id %}">{{p.title | title}} </a>--{{p.description|truncatewords:3 }}</p>
    -->
      {% endfor %}

      
   </table> -->

   Main Section
  <main class="projects">
   <section class="hero-section text-center">
     <div class="container container--narrow">
       <div class="hero-section__box">
         <h2>Search for <span>Projects</span></h2>
       </div>

       <div class="hero-section__search">
         <form class="form" action="#" method="get">
           <div class="form__field">
             <label for="formInput#search">Search By Projects </label>
             <input class="input input--text" id="formInput#search" type="text" name="text"
               placeholder="Search by Project Title" />
           </div>

           <input class="btn btn--sub btn--lg" type="submit" value="Search" />
         </form>
       </div>
     </div>
   </section>
   <!-- Search Result: DevList -->
   <section class="projectsList">
     <div class="container">
       <div class="grid grid--three">

         {% for p in projects %}
         <div class="column">
           <div class="card project">
             <a href="{% url 'projects:project' p.id %}" class="project">
               <img class="project__thumbnail" src="{{p.image.url}}" alt="project thumbnail" />
               <div class="card__body">
                 <h3 class="project__title">{{p.title|slice:"20"}}</h3>
                 <p><a class="project__author" href="">By Dennis Ivanov</a></p>
                 <p class="project--rating">
                   <span style="font-weight: bold;">{{p.vote_ratio}}%</span> Postitive
                   Feedback ({{p.vote_total}}Votes)
                 </p>
                 <div class="project__tags">
                  {% for tag in p.tags.all|slice:"3" %}
                   <span class="tag tag--pill tag--main">
                     <small>{{ tag }}</small>
                   </span>
                  {% endfor %}
                 
                 </div>
               </div>
             </a>
           </div>
         </div>
         {% endfor %}

       

         

         


        

       </div>
     </div>
   </section>
   {% include 'pagination.html' with queryset=projects custom_range=custom_range  %}

 </main>


   


{% endblock %}

templates/single-project.html
{% extends 'main.html'  %}

{% block content %}
   <p>List of Projects</p> 
   <table style="border: 2px groove blue;">
      <tr >
         <th>ID</th>
         <th>Project Name</th>
         <th>Votes</th>
         <th>Positive Votes (%)</th>
         <th>View</th>
      </tr >
      {% for p in projects %}
         <tr>
            <td>
               {{p.id}}
            </td>
            <td>
               {{p.title}}
            </td>
            <td>
               {{p.vote_total}}
            </td>
            <td>
               {{p.vote_ratio}}
            </td>
            <td>
               <a href="{% url 'projects:project' p.id %}">view</a>
            </td>
            <td>
               <a href="{% url 'projects:update-project' p.id %}">Edit</a>
            </td>
            <td>
               <a href="{% url 'projects:delete-project' p.id %}">Delete</a>
            </td>
            
         </tr>
                                    
         <!-- <p> -- <a href="{% url 'projects:project' p.id %}">{{p.title | title}} </a>--{{p.description|truncatewords:3 }}</p>
    -->
      {% endfor %}

      
   </table>

   <!-- Main Section -->
  <main class="projects">
   <section class="hero-section text-center">
     <div class="container container--narrow">
       <div class="hero-section__box">
         <h2>Search for <span>Projects</span></h2>
       </div>

       <div class="hero-section__search">
         <form class="form" action="#" method="get">
           <div class="form__field">
             <label for="formInput#search">Search By Projects </label>
             <input class="input input--text" id="formInput#search" type="text" name="text"
               placeholder="Search by Project Title" />
           </div>

           <input class="btn btn--sub btn--lg" type="submit" value="Search" />
         </form>
       </div>
     </div>
   </section>
   <!-- Search Result: DevList -->
   <section class="projectsList">
     <div class="container">
       <div class="grid grid--three">

         {% for p in projects %}
         <div class="column">
           <div class="card project">
             <a href="{% url 'projects:project' p.id %}" class="project">
               <img class="project__thumbnail" src="{{p.image.url}}" alt="project thumbnail" />
               <div class="card__body">
                 <h3 class="project__title">{{p.title|slice:"20"}}</h3>
                 <p><a class="project__author" href="">By Dennis Ivanov</a></p>
                 <p class="project--rating">
                   <span style="font-weight: bold;">{{p.vote_ratio}}%</span> Postitive
                   Feedback ({{p.vote_total}}Votes)
                 </p>
                 <div class="project__tags">
                  {% for tag in p.tags.all|slice:"3" %}
                   <span class="tag tag--pill tag--main">
                     <small>{{ tag }}</small>
                   </span>
                  {% endfor %}
                 
                 </div>
               </div>
             </a>
           </div>
         </div>
         {% endfor %}

       

         

         


        

       </div>
     </div>
   </section>

 </main>


   


{% endblock %}

templates/update-project.html
{% extends 'main.html' %}
{% block content %}

   <form action="" method="POST" enctype="multipart/form-data" >
       {% csrf_token  %}
       {{ project_form.as_p }}
       <input type="submit" value="Confirm">

   </form>

{% endblock %}